### ISSUE TITLE
Add a `Styled` component

### ISSUE THREAD

**Issue by petehunt** [jsxstyle/jsxstyle#147] opened 2020-07-02 08:46 UTC
Styling inputs with jsxstyle sort of sucks. I made a component that makes it easier:

```
<Styled
      width="100%"
      background={Colors.COLOR_4}
      color={Colors.COLOR_1}
      padding="10px 20px"
    >
      <input type="text" placeholder="say something..." />
</Styled>
```

Seems like a thing that we could include in jsxstyle.

Implementation (does not support style extraction):
```
import { JsxstyleProps, cache } from "jsxstyle";
import { ReactElement } from "react";
import React from "react";

type IntrinsicElement = keyof JSX.IntrinsicElements;
type ValidComponentPropValue =
  | undefined
  | false
  | null
  | IntrinsicElement
  | React.StatelessComponent<any>
  | React.ComponentClass<any>;

export function Styled<C extends ValidComponentPropValue>({
  children,
  ...style
}: Omit<JsxstyleProps<C>, "component"> & { children: ReactElement }) {
  return (
    <>
      {React.Children.map(children, (child) =>
        React.cloneElement(child, {
          className: cache.getClassName(style, child.props.className),
        })
      )}
    </>
  );
}
```

**Comment by meyer** [comment] 2021-07-18 00:25
Sorry for the delay! I’ve been thinking about this one for a while. I’m into the concept but I have some thoughts/concerns:

😓 
- I’m not wild about the `cloneElement` usage.
- This makes static analysis quite difficult if the `Styled` component contains dynamic children. Could warn about it in `jsxtyle-webpack-plugin` though, so not super concerning.
- If a component doesn’t do anything with a `className` prop it will remain unstyled. This is a problem with the current `component` prop as well, so also not super concerning.

😍 
- Being able to style multiple children with the same styles is pretty cool.
- Component props and style props get to both be top-level (at long last!).

---

Styling inputs does suck, and it’s something I’ve been exploring a bit for jsxstyle 3. Up until now, jsxstyle has basically just swapped style props and component props.

Instead of writing code like this:

```jsx
<input
  type="text"
  value="Hello"
  style={{
    display: 'block',
    color: 'purple',
  }}
/>
```

you write code like this:

```jsx
<Block
  component="input"
  props={{
    type: 'text',
    value: 'Hello',
  }}
  color="purple"
/>
```

If you think of the styles as an object and component props as an object, the style object is usually going to contain more stuff, so moving it to the top level feels like the right thing to do. Swapping styles and component props isn’t necessarily better than what it’s replacing though—it’s just an API with a different set of priorities. Components that require a lot of props all of a sudden become a real chore to style.

### Separating component props from style props

Here’s an assumption I’m making: we want component props and style props at the same level.

```jsx
<Block
  component="input"
  type="text"
  value="Hello"
  color="purple"
/>
```

If we had an allowlist of all component props, we’d be able to keep both component props and style props at the top level. With some runtime hacks we can actually get a list of all possible style props and then use that to separate component props from style props. The problem is that it’s not consistent, which means the types would potentially be lying to you and runtime implementations would differ slightly across each browser.

We could ask users for that list of props but this just seems like a different version of the same suckage:

```jsx
<Block
  component="input"
  componentProps={['type', 'value']}
  type="text"
  value="Hello"
  color="purple"
/>
```

### The solution (?)

What if we kept an array of common _component_ props? Here’s a rough example:

```tsx
import React from 'react';

const commonProps = [
  'id',
  'name',
  'placeholder',
  'type',
  'value',
] as const; // `as const` is necessary to make `CommonProp` nice and specific

// our common props as a union of strings
type CommonProp = (typeof commonProps)[number];

// a union of all HTML element names
type IntrinsicElement = keyof JSX.IntrinsicElements;

interface JsxstyleProps<T> extends React.CSSProperties {
  component?: T;
}

// this is where the magic happens
type ComponentProps<T extends IntrinsicElement> = Pick<
  JSX.IntrinsicElements[T],
  Extract<keyof JSX.IntrinsicElements[T], CommonProp>
>;

const Example = <C extends IntrinsicElement = 'div'>(
  props: JsxstyleProps<C> & ComponentProps<C>
): JSX.Element | null => {
  // TODO: implementation :D
  return null;
};
```

If you want to mess around with this a bit, here’s a [TypeScript playground](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAJQKYEMDG8BmUIjgcilQ3wG4BYAKCrQgDsBneWkEegBRzAbgF44A2lTgiCKAK4wIaFGGAwUAG2AAvJPgA0w0fglSWYRUhjqtlUWMkRM08Q03aR+NAAskaANZIAJg-M7aRXszC3xvYAYUACMjXxCdYDjHAjoUEFNk-EN0JBcIRW8kKD9QohRvekUATxKdIgBHcWAiJP8nHAB3YMyYKrAMtoIANyVxAYBdOBQeWkYYCmpKXv64AEk6GChgRmA0AFEjdI2+OC8q6zgAKQBlAA0AOnXN7YZdg6QjmAYFqm2TKEwOSuDAAHkwqkZOBBuAAeAAqAD44EgQSY6N4eMh0DB7gBha7XKH9WDAJA8ADeyQM9CQGwA-AAuOBwhYAXyoVGWSDguNwbDoRJOAAouRcWPyiQwAJQCOjiEBRIrjH5LPrc3ngGkbSXw5Go2kYtYbLY7faHWkwJH8di7Dwwm4PJ4m15mj4WhgCOHjDRwPaoqDYmFnC4Ox7Gl5vc0bD1en0aiVcBEIlWzJi+kFpQzc-gw3F6tGGp0R12fE5hYBDfAIoVgLgMJmXUHgyF13NIgBkPNwkDoFp1uIRUobd3u71LAB84HLFIo+EjKYMAPSL5kAeQAIqumaAs58UDBgPQ4Az18kiDBxFA6FPxDO2SqYX7M0ZtNTexteAAibZgSSf7Rcl+Jiov+-gjIoYxfgAEkgVRwDAbhEKBIiBNAX4tKBi7JhylCPhm4Avv4b4Wl+4RDMh8FqqRFY8BUdD4PALgoEM3IoJRKy1tCmHYYseHPkgAFUZ+ZG0fQDFwExLFTOx3KcWA3GkEAA) with a functioning example.

This array of common props wouldn’t be perfect, so we could allow users to provide a `componentProps` array to add to the internal array of common props. The hope would be that we’d be able to remove the need for a `componentProps` prop for the majority of users.

We could also auto-allow all aria/a11y-related props. I think we might do something like this already? 🤔

I like the simplicity, and we already do something like this for pseudoelement and pseudoclass prefixes.

Let me know what you think!

**Closed** 2021-07-21 02:20 UTC
